
import { Applicant } from './types';

export const MOCK_APPLICANTS: Applicant[] = [
  {
    id: '1',
    fullName: 'Arjun Mehta',
    email: 'arjun.mehta@example.com',
    phone: '+91 98765 43210',
    city: 'Mumbai',
    college: 'IIT Bombay',
    degree: 'B.Tech',
    branch: 'Computer Science',
    graduationYear: 2025,
    skills: ['React', 'Node.js', 'TypeScript', 'Tailwind'],
    experience: 'Software Intern at TechCorp',
    projects: 'Built a real-time chat application',
    linkedin: 'linkedin.com/in/arjun',
    resumeUrl: '#',
    status: 'Pending',
    appliedPosition: 'Frontend Engineer Intern',
    appliedDate: '2024-03-20',
    lastUpdated: '2024-03-20'
  },
  {
    id: '2',
    fullName: 'Priya Sharma',
    email: 'priya.s@example.com',
    phone: '+91 87654 32109',
    city: 'Bangalore',
    college: 'BITS Pilani',
    degree: 'B.E.',
    branch: 'Electronics',
    graduationYear: 2024,
    skills: ['Python', 'Django', 'PostgreSQL', 'AWS'],
    experience: 'ML Research Intern',
    projects: 'Image classification model for medical diagnostics',
    github: 'github.com/priya',
    resumeUrl: '#',
    status: 'Interview Scheduled',
    appliedPosition: 'Backend Engineer Intern',
    appliedDate: '2024-03-18',
    lastUpdated: '2024-03-21'
  },
  {
    id: '3',
    fullName: 'Rohan Gupta',
    email: 'rohan.g@example.com',
    phone: '+91 76543 21098',
    city: 'Delhi',
    college: 'Delhi Technological University',
    degree: 'B.Tech',
    branch: 'Information Technology',
    graduationYear: 2025,
    skills: ['Figma', 'UI/UX', 'React Native'],
    experience: 'Product Design Intern',
    projects: 'Redesigned a local grocery delivery app',
    portfolio: 'rohan.design',
    resumeUrl: '#',
    status: 'Shortlisted',
    appliedPosition: 'Product Design Intern',
    appliedDate: '2024-03-15',
    lastUpdated: '2024-03-19'
  },
  {
    id: '4',
    fullName: 'Ananya Iyer',
    email: 'ananya.i@example.com',
    phone: '+91 65432 10987',
    city: 'Chennai',
    college: 'Anna University',
    degree: 'M.Tech',
    branch: 'Data Science',
    graduationYear: 2024,
    skills: ['PyTorch', 'SQL', 'Scikit-learn'],
    experience: 'Data Analyst at Finance firm',
    projects: 'Stock market prediction using LSTM',
    resumeUrl: '#',
    status: 'Approved',
    appliedPosition: 'Data Science Intern',
    appliedDate: '2024-03-10',
    lastUpdated: '2024-03-22'
  },
  {
    id: '5',
    fullName: 'Vikram Singh',
    email: 'vikram.s@example.com',
    phone: '+91 54321 09876',
    city: 'Jaipur',
    college: 'MNIT Jaipur',
    degree: 'B.Tech',
    branch: 'Computer Science',
    graduationYear: 2026,
    skills: ['Java', 'Spring Boot', 'Microservices'],
    experience: 'Open source contributor',
    projects: 'Distributed caching system implementation',
    resumeUrl: '#',
    status: 'Rejected',
    appliedPosition: 'Backend Engineer Intern',
    appliedDate: '2024-03-05',
    lastUpdated: '2024-03-07'
  }
];
